### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#295]
The application could benefit from having international language translation files so that the scope of users of the application is useful to increases.  There is a great desire by ethnic populations to use software in their native language worldwide.

https://milesm.pythonanywhere.com/wiki/default/index/international

For Spanish / Espanol - I could assist in the maintenance of the es.py file

**Comment by NerdsLogic** [comment]
It looks like the translate function is already wrapped around nearly everything that needs it, so only creating the various language files and including them with the application files is required along with instructions to the user on enabling the available additional languages.

I've begun to populate an es.py file for Spanish/Espanol - Is this a project?  Should this issue be assigned to me?

**Comment by NerdsLogic** [comment]
The Spanish Translation file for es.py has been added to the /languages folder of my fork.

**Comment by NerdsLogic** [comment]
If there is any immediate desire for a language translation file other than Spanish at this time?
I created a hotkeys utility to greatly speed up the language file creation by crawling the list of phrases that need translation and fetch translations for them from translate.google.com and input into the edit language webform you create for your respective language at http://127.0.0.1:8000/admin/design/openstudio#languages

**Comment by NerdsLogic** [comment]
Function for forcing localization?  ie:
studio.openstudio.com/en/ = English
studio.openstudio.com/de/  = Deutsch
studio.openstudio.com/es/ = Espanol

**Comment by edwinvandeven** [comment]
I think there's no pressing need for any additional translations at the moment, though I think it might be a good idea to change the code a little bit. Instead of something like T("Save"), something like T("app_general_save") and then app_general_save: Save in langues/default.py might be the way to go. This way all the strings to be translated will already be in one file and it'll be easier to add new translations in the future and check the completeness of translations.
I would suggest that this should become the default workflow when programming.

The w2p translation system has options to force the language for a session. I don't want to change the urls at the moment, there is still a little bit of dirty Ajax javascript here and there that relies on hard coded urls. That should be straightened out first.

**Comment by labeldevops** [comment]
What is the status for this? I would like to add translation files for at least one more language. Are the areas you mentioned cleaned out and is everything "safe for translation"?

**Comment by MatthijsCornil** [comment]
From what I can tell, the issue that NerdsLogic mentioned is still there (the menu items don't translate while all the rest does). 
The Ajax issue I don't know. @labeldevops, what language were you wanting to add? I've made an nl.py file that should be mostly complete.
