### ISSUE TITLE
Bad Gateway when attempting to print Event Ticket

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#346]
When attempting to print an event ticket by clicking on the PDF button in /Events - the page wheels perpetually until 504 bad gateway is returned.

This is related to the pyqrcode module.  If the module is not installed, a trouble ticket for import error of the module.  After installing the module, the application will hang when requesting the PDF.  Source of problem is believed to live in controllers/events.py  Installing pypng (mentioned in docs for pyqrcode) does not change the outcome.

**Comment by edwinvandeven** [comment]
The system requirements have been updated so "pyqrcode" is mentioned instead of "qrcode" 
Though I seem to be unable to reproduce this issue. The 504 bad gateway might indicate a timeout of nginx while waiting for a response from uwsgi. 
Have you tried restarting uwsgi after installing the module? (Though this shouldn't make a difference).

**Comment by NerdsLogic** [comment]
Yes, uwsgi and as well the host have been restarted.

**Comment by edwinvandeven** [comment]
Does this also happen when you run it locally on your laptop for example?
I still haven't been able to reproduce this issue... when running it from a local terminal there might be some output in the terminal that could point us in the direction of a solution
